version: '3.8'

services:
  mongodb:
    image: mongo:6.0.3  # ✅ Specify a stable version
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dream-app
    ports:
      - "4000:3000" 
    environment:
      - MONGO_URI=mongodb+srv://vikash29raj:mongodb@cluster0.iga7u.mongodb.net/dreams?retryWrites=true&w=majority

    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
